### ISSUE TITLE
Als beheerder wil ik kunnen werken met Git

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/api-beheer#1]
**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg voor een sprint
- [x] Product Owner akkoord en voorzien van prio
- [x] Voorzien van Definition of Done
- [x] Voorzien van Acceptatiecriteria
- [x] Voorzien van taken
- [x] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

- [ ] Kunnen werken met Github

**Acceptatiecriteria**

- [ ] Geschikt voor alle beheerders/projectmedewerkers 

**Taken**

- [ ] Comments op tutorial Frank langs Joeri (@michielverhoef @joeribekker) Wellicht mogelijk met 
- [x] Tutorial updaten en in beheer nemen
- [x] On the job

**Comment by joeribekker** [comment]
Doorgenomen, aanpassingen voorgesteld: https://github.com/VNG-Realisatie/Tutorial/pull/11/files

Moet heel eerlijk zeggen dat het werken met Github ik aan jullie over laat wat het beste werkt. Ik werk daar niet vaak direct mee, maar bijna altijd via `git` op de commandline.

**Comment by melsk-r** [comment]
Het grootste deel van de aanpassingen is prima. De wijzigingen in het commit deel verraden echter dat jij meer gebruik maakt van de commandline. Ik heb geen idee of wij ook zo gaan werken en of dit dan ook zo gedocumenteerd moet worden. Wellicht is een toevoeging dat de beschrijving is gebaseerd op het werken met de commandline al voldoende. Ik heb het even aan Frank Samwel voorgelegd.

**Comment by joeribekker** [comment]
@melsk-r Ik heb develop branch toevoeging ongedaan gemaakt, kan jij beslissen of deze aanpassingen handig zijn of niet en dan het PR goed of afkeuren: https://github.com/VNG-Realisatie/Tutorial/pull/11/

**Comment by michielverhoef** [comment]
Ik ben er wel voor om de commandline versie van git te gebruiken of in ieder geval te beheersen. De kans is groot dat gebruikers van de standaard (ontwikkelaars) dit ook doen en dan moeten de beheerders weten hoe en of het werkt.

**Comment by michielverhoef** [comment]
Het is even wennen maar zodra je door hebt dat de lokale commando's op de prompt zijn en alles wat je met github doet via de browser gaat is het best simpel.

**Comment by melsk-r** [comment]
@michielverhoef Ik vind het prima om (ook) met de commandline te werken. Vergt alleen even wat inwerktijd. Is het verstandig om ook hiervoor een korte beschrijving maken zoals we dat met Docker ook hebben gedaan?

**Comment by melsk-r** [comment]
Michiel en ik gaan kijken of het begrip dat Michiel inmiddels van Git en GitHub heeft over te dragen is voor zover Robert zijn kennis niet ook al voldoet.

**Comment by TCIMEddy** [comment]
@melsk-r Ik ga deze user story sluiten, want hij is te algemeen en vaak heeft het betrekking op kennis op doen on the job. Er is geen discussie over het gebruik van GIT. Komt er een concrete actie dan graag opnemen als user story met prio
