### ISSUE TITLE
Beschikbaarheid "haven" / "werkbank"

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-beheer#102]
# Impediment

Besluit inzake inrichting werkbank

**Comment by TCIMEddy** [comment]
@kciredor (ter info voor @melsk-r) kun je aangeven wat je precies gaat doen en of dit in de huidige sprint lukt?

**Comment by kciredor** [comment]
Hi,

Het nieuwe Haven kanban board staat open. Indeling is nog heel ruw en veranderlijk op dit moment, het bestaat pas sinds gisteren. Je moet ergens beginnen :-). Link: https://gitlab.com/commonground/haven/boards/963655

Ik zal mijn "Haven - Visie en Strategie" document met jullie delen per mail. Hierin staat omschreven hoe we tot Haven gaan komen. De Haven planning loopt niet synchroon met sprint plannings, dat gaat niet. Van belang is dat Haven als concept pas bestaat sinds twee dagen. Alles moet nu ontwikkeld en opgezet gaan worden.

In de context van team "API Beheer" is als eerste aan de orde dat wordt vastgesteld wat het team exact nodig heeft. Hoe ziet de benodigde beheeromgeving er uit? Wat lossen we op? Laten we dat samen maandag doornemen.

Groet, Roderick

**Comment by kciredor** [comment]
We gaan verder in #63 en daarmee sluit ik deze.
