### ISSUE TITLE
Als beheerder wil ik een algemene werkwijze die voor alle API standaarden te gebruiken is

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/api-beheer#11]
Zodat niet bij elke nieuwe standaard het wiel opnieuw uitgevonden moet worden

**Definition of ready**

- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg voor een sprint
- [ ] Product Owner akkoord en voorzien van prio
- [ ] Voorzien van Acceptatiecriteria
- [ ] Voorzien van Definition of Done
- [ ] Voorzien van taken
- [ ] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [ ] ...
- [ ] ...

**Oplossingsrichting**

...

**Acceptatiecriteria**

- [ ] Niet belemmerend werken voor beheer andere standaarden
- [ ] ...

**Taken**

- [ ] ... (@...)
- [ ] ... (@...)

**Comment by TCIMEddy** [comment]
We hebben hier uitgebreid over gesproken en het is in ieder geval een algemeen acceptatiecriterium geworden
