### ISSUE TITLE
Als beheerder wil ik weten tegen welke problemen ik aan kan lopen op DockerHub/Haven en hoe ik daar dan op moet handelen

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/api-beheer#129]
...zodat ik weet hoe deze kan tackelen als deze zich voordoen.

**Toelichting**
Dit kan als een soort FAQ/Cookbook groeien?

**Definition of ready**

- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg voor een sprint
- [ ] Product Owner akkoord en voorzien van prio
- [ ] Voorzien van Acceptatiecriteria
- [ ] Voorzien van Definition of Done
- [ ] Voorzien van taken
- [ ] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [ ] ...
- [ ] ...

**Oplossingsrichting**

...

**Acceptatiecriteria**

- [ ] Niet belemmerend werken voor beheer andere standaarden
- [ ] ...

**Taken**

- [ ] ... (@...)
- [ ] ... (@...)

**Comment by melsk-r** [comment]
@michielverhoef Ik vermoed dat deze story gelijk is aan #22. Zo ja dan kunnen we deze sluiten.

**Comment by michielverhoef** [comment]
Zo te zien ook. Was ook te verwachten, dit is er eentje uit het lijstje user stories die we gemaakt hadden tijdens het fieldlab laatst. Daar zaten mogelijk dingen bij die we al hadden.

Ik sluit dit issue.
