### ISSUE TITLE
Wat gaan we doen met de backlog van ZGW nadat de ZGW APi's in beheer zijn genomen

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/api-beheer#138]
De API's zijn relatief zelfstandige eenheden, in de zin dat een API (RI + documentatie) in een aparte repository staat.

De backlog aan user stories voor de ZGW API's staat echter in een aparte, gezamelijke repository, GEMMA Zaken. 

Blijft de backlog daar of gaan we deze opsplitsen naar de API waar de user stories over gaan?

**Comment by melsk-r** [comment]
Kunnen we niet stellen dat we er voorlopig vanuit gaan dat we de backlog as-is over gaan nemen. Dan krijgen we door er mee te werken vanzelf meer gevoel voor wat het handigste is. 
Op basis waarvan moet ik hierover nu anders een beslissing nemen?

Of zie jij nu al duidelijke voordelen voor het opsplitsen?

**Comment by michielverhoef** [comment]
Voorlopig overnemen as-is lijkt mij ook het beste. Veel user stories zullen meerdere componenten raken en dan is het toch lastig te bepalen in welke repository het issue moet komen.

**Comment by michielverhoef** [comment]
Aangezien we het eens zijn heb ik het issue maar gesloten :-D
