### ISSUE TITLE
Gitlab of Github?

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/api-beheer#140]
Deels verwant aan #139 

Een aantal CG trajecten (waaronder NLX, Haven en developer.overheid.nl) zit al op Gitlab, onder andere vanwege de betere CI/CD mogelijkheden.

Tijdens het ontwikkelen is het niet handig maar het in beheer nemen van een API standaard zou wel een natuurlijk moment zijn om een repository eventueel over te zetten. Wat is wijsheid, ook met het oog op de doorontwikkeling van de standaarden.

**Comment by melsk-r** [comment]
We hebben dit afgelopen maandag bij het 'API Beheer na 18 juli' overleg besproken. Roderick gaf toen aan om het voorlopig te houden bij wat het nu is. Op een later moment kunnen we nog altijd overstappen.
Daarmee voorkomen we dat we, in een situatie waarin nog heel veel onduidelijk is, het overzicht kwijtraken doordat we er zaken bij slepen die nog niet persé noodzakelijk zijn.

Ik zal dit issue daarom voorlopig sluiten.
