### ISSUE TITLE
Als beheerder wil ik weten welke partijen bij de ontwikkeling van een standaard betrokken zijn geweest

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/api-beheer#19]
zodat ik vragen kan stellen over aspecten/ontwerp beslissingen van de API

**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg voor een sprint
- [x] Product Owner akkoord en voorzien van prio
- [x] Voorzien van Acceptatiecriteria
- [x] Voorzien van Definition of Done
- [x] Voorzien van taken
- [x] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [x] Documentatie wie de ontwikkelaar(s) is/zijn met daarin alle informatie zodat ik vragen kan stellen.
- [x] Lijst bevat:
   - contactpersoon organisatie
   - namen deelnemende personen
   - rol in het project van de deelnemende personen
   - welke projecten zijn ze betrokken geweest

**Acceptatiecriteria**

- [x] Niet belemmerend werken voor beheer andere standaarden
- [x] Vindbaar en opgenomen in standaard documentatie
- [x] Informatie is actueel

**Taken**

- [x] Template maken online (@melsk-r )
- [x] Procedure beschrijven in beheer.md (@melsk-r )
- [ ] Repository? (@michielverhoef)
- [x] PR Template (@melsk-r)
- [x] Invullen template (@joeribekker)
- [x] Voorbeeld template maken beheer.md (@TCIMEddy)

**Comment by TCIMEddy** [comment]
@melsk-r Ik heb het zo duidelijk en specifiek mogelijk gemaakt. Als jij akkoord bent wil je dit dan afvinken en in ready for sprint zetten (en daar dan ook het vinkje voor zetten)

**Comment by michielverhoef** [comment]
Willen we de zoekactie ook om kunnen draaien? Dus weten bij welke standaarden een bepaalde leverancier allemaal betrokken is geweest? Dan heb je het al snel over een matrix met filter en sorteermogelijkheden.
In excel is dat zo gemaakt maar in markdown niet (denk ik?).

**Comment by melsk-r** [comment]
Dit lijkt me voorlopig niet de hoogste prioriteit te hebben.
Maar ik denk dat dit redelijk eenvoudig te realiseren is door de juiste wijze van registratie te kiezen.

**Comment by melsk-r** [comment]
@joeribekker, ik heb het markdown bestandjes 'Deelnemende partijen.md' aangemaakt in de root van de API beheer repository. Kan jij dit vullen en kijken of het voldoet.

Ik vraag me af of zo'n lijstje met het oog op AVG wel toegestaan is. Contactgegevens heb ik er daarom al niet aan toegevoegd.

**Comment by michielverhoef** [comment]
@melsk-r :
https://github.com/VNG-Realisatie/Architectuur-en-Standaarden
Deze repository  bestaat al en is bedoeld voor overkoepelende informatie, kunnen we die hiervoor gebruiken?

**Comment by melsk-r** [comment]
@TCIMEddy, wat wordt bedoelt met de taak PR Template?

**Comment by TCIMEddy** [comment]
Template via PR doen en vragen om feedback bij team

**Comment by joeribekker** [comment]
@melsk-r Dat zou neerkomen op:

Organisatie | Project | Persoon | Rol 
--- | --- | --- | ---
VNG / Dimpact | ZDS 2.0 | Hugo ter Doest | Product owner
VNG | ZDS 2.0 | Eddy Timmer | Scrum master
VNG | ZDS 2.0 | Wishal Gokoel | Project manager / Contactpersoon
VNG / Maykin Media | ZDS 2.0 | Sergei Maertens | Ontwikkelaar
VNG / Maykin Media | ZDS 2.0 | Joeri Bekker | Ontwikkelaar
VNG | ZDS 2.0 | Jeffrey Gortmaker | Architect
VNG | ZDS 2.0 | Arjan Kloosterboer | Architect
Gemeente Haarlem | ZDS 2.0 | Eelco Hotting | Stakeholder
Gemeente Delft | ZDS 2.0 | Rita | Stakeholder
Gemeente Utrecht | ZDS 2.0 | Constantijn | Stakeholder
Gemeente Amsterdam | ZDS 2.0 | Marcel Moermans | Stakeholder
Gemeente Rotterdam| ZDS 2.0 | Ruub | Stakeholder

* Project lijkt me eerder een kopje worden.
* Stakeholder vind ik wat vaag. Kan iedereen zijn?
* Ik mis rollen: teamlid / ontwikkelaar / architect
* Is organisatie altijd VNG, of....? Ook wij worden ingehuurd via VNG :) Ik heb het nu met een "/" aangegeven maar bij Hugo is dat bijvoorbeeld weer verwarrend.

PS. Je kan voor een tabel ook 3 streepjes gebruiken onder de kopjes. Het hoeft niet dezelfde lengte te hebben.

**Comment by melsk-r** [comment]
@joeribekker Ik heb je voorstel alvast verwerkt in het betreffende bestand.

**Comment by melsk-r** [comment]
@TCIMEddy, Ik heb eerlijk gezegd geen idee wat ik met de taak 'PR Template' moet.

**Comment by TCIMEddy** [comment]
@melsk-r Ik weet niet precies wat je bedoelt

**Comment by melsk-r** [comment]
@TCIMEddy Nou 1 van de taken in dit issue is 'PR Template'. Dat is aan mij toegekend maar ik heb geen idee wat ik daar aan zou moeten doen en of ik daar uberhaupt nog wel iets aan moet doen.

**Comment by michielverhoef** [comment]
@melsk-r  Wordt met die taak niet bedoeld dat je een pull request (PR) moet doen van het template? Zodat in deze repository een template opgenomen wordt wat in een API project gebruikt en ingevuld kan worden?

**Comment by michielverhoef** [comment]
Een team kan in de loop van de tijd veranderen van bezetting. Omdat we willen weten wie er bij de ontwikkeling betrokken is (geweest) lijkt het mij goed om deelnemers niet te verwijderen.  Anders weet je nog niet wie er nou aan een standaard meegewerkt hebben. Als we dit willen, moet er dan een periode bij?

**Comment by melsk-r** [comment]
> @melsk-r Wordt met die taak niet bedoeld dat je een pull request (PR) moet doen van het template? Zodat in deze repository een template opgenomen wordt wat in een API project gebruikt en ingevuld kan worden?

Ik denk dat dit niet meer van toepassing is. Het document staat immers al in dit project.

**Comment by melsk-r** [comment]
> 
> 
> Een team kan in de loop van de tijd veranderen van bezetting. Omdat we willen weten wie er bij de ontwikkeling betrokken is (geweest) lijkt het mij goed om deelnemers niet te verwijderen. Anders weet je nog niet wie er nou aan een standaard meegewerkt hebben. Als we dit willen, moet er dan een periode bij?

Ik ben het met je eens dat deelnemers niet verwijderd moeten worden. Misschien moeten we er idd een periode bij zetten al verwacht ik dat het bijhouden daarvan regelmatig vergeten zal gaan worden.

**Comment by melsk-r** [comment]
Ik stel voor om de toevoeging van periode en rol per periode in een andere userstory te plaatsen.
Dit issue kunnen we dan sluiten en het nieuwe kunnen we dan tzt in sprint nemen.

**Comment by melsk-r** [comment]
In de beschrijving van dit issue staat bij *Specifiek*
 
- [ ] Lijst bevat:
   - contactpersoon organisatie

Ik denk dat we deze weg moeten laten omdat we dan beheer moeten gaan voeren op een persoon die geen rol gespeeld hoeft te hebben in het project en omdat contactpersoon van een organisatie nog wel eens aan verandering onderhevig kan zijn en we dat continue moeten gaan monitoren. Heeft weinig zin n.m.m.

Verder staat er bij *Taken*:

- [ ] Repository? (@michielverhoef)

Geen idee meer wat we daarmee wilden. Voorlopig moeten we per project gewoon een lijstje bijhouden lijkt me. Op termijn kunnen we misschien een efficiëntere manier hanteren.

Indien iedereen zich hierin kan vinden dan kunnen we dit issue sluiten.

**Comment by TCIMEddy** [comment]
@joeribekker Kun je dit lijstje opnemen in de repo van zgw? Dan is deze user story gereed.

**Comment by TCIMEddy** [comment]
@melsk-r Vraag jij Cathy of zij dit wil regelen.

**Comment by michielverhoef** [comment]
je kunt het ook bij de scrum master neerleggen, die regelt het dan bij de rest van het team?

**Comment by melsk-r** [comment]
@michielverhoef In principe dat eerste maar ik denk dat dit gewoon een eis moet worden voor het in beheer nemen van een API standaard. In dat geval zal dit bij overdracht geregeld moeten zijn.
Ik zal het daarbij vermelden. @TCIMEddy: Dat betekent dat ik geen verzoek hoef te doen.

De taak 'Repository?' staat nog open. Laten we het plaatsen van dit lijstje in de ZGW repositories maar als laatste actiepunt van dit issue beschouwen. @joeribekker Ik denk dat dit per API zal moeten, niet?
