### ISSUE TITLE
Als beheerder wil ik API beheerkennis op doen

### ISSUE THREAD

**Issue by wishalg** [VNG-Realisatie/api-beheer#2]
zodat ik api-beheer adequaat kan uitvoeren

**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg voor een sprint
- [x] Product Owner akkoord en voorzien van prio
- [x] Voorzien van Acceptatiecriteria
- [x] Voorzien van Definition of Done
- [x] Voorzien van taken
- [x] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [ ] Beheerders moeten over voldoende kennis kunnen beschikken die nodig is om standaarden en referentie implementaties te beheren.
- Denk daarbij aan: 
  -  [ ] Python #62
  -  [ ] Docker #61
  -  [ ] Jenkins #60
  -  [ ] GitHub #1 

- [ ] Een overzicht hebben van de onderlinge afhankelijkheden en volgordes van deze systemen/onderdelen

afhankelijk van nog te nemen beslissingen:
  - Enterprise Architect
  - Imvertor

**Acceptatiecriteria**

- [ ] Niet belemmerend werken voor beheer andere standaarden
- [ ] Beheerders dienen aantoonbaar over de noodzakelijke kennis te beschikken (hoe is mij nog even niet duidelijk).
- [ ] ...

**Taken**

- [ ] Inventarisatie van de benodigde kennis. (@...)
- [ ] Bepalen van de minimaal benodigde kennis voor beheeroverdracht. (@...)
- [ ] Bepalen van de wijze waarop deze kennis wordt overgedragen dan wel verkregen. (@...)
- [ ] Overdracht van de kennis (@...).

**Comment by TCIMEddy** [comment]
@melsk-r Staat in ready maken, wie assign je?

**Comment by melsk-r** [comment]
@joeribekker, kan jij alvast eens kijken of we nog wat missen en ook even aangeven welke kennis het handigste is om als eerste over te kunnen beschikken.

**Comment by joeribekker** [comment]
* Kubernetes (omgeving waar Docker containers in draaien)
* OAS (specificatie van de APIs)
* Postman (Hulpmiddel om de APIs te testen - en voor het Test platform)

Jenkins zou wellicht iets algemener kunnen, zoals CI/CD-tooling. Maar we gebruiken nu inderdaad Jenkins. Persoonlijk vind ik Python kennis ook optioneel. Als het niet werkt, moet de API dev het maar fixen.

Vooruitlopend zou ik als beheerder het volgende willen kunnen doen:

1a. oas3 valideren (inhoudelijke kennis niet verplicht)
1b. documentatie is bijgeleverd en bijgewerkt?
2. ref. impl. docker pull / docker run moet werken (inhoudelijke kennis niet verplicht)
3. testsuite draaien in test platform
4. iedereen eens met deze versie? in beheer!

beheer:
1. publish oas en docs op webpagina met versienummer
2. deploy ref impl.
3. voeg testsuite toe aan test platform

**Comment by melsk-r** [comment]
@joeribekker, Blijkbaar heb jij iets andere denkbeelden bij het beheer van de standaarden dan Michiel en ik. Ik denk dat het goed is om dat samen eens te bespreken zodat wij de door ons te bewandelen weg goed kunnen uitstippelen.

**Comment by TCIMEddy** [comment]
@melsk-r Wat mij betreft ready for sprint, dus ik zet hem in review op jouw naam

**Comment by joeribekker** [comment]
Aantekening beheer proces

Oudere versie (1.1)
Oudere versie (1.2)
- Geen ondersteuning meer

Deprecated versie (2.4)
- Ondersteuning voor vragen
- Ondersteuning in referentie implementatie
- Alleen veiligheids issue kunnen zorgen voor een 2.5

Huidig versie  (3.1)
- Ondersteuning voor vragen
- Issues komen op de roadmap voor minor/major

Toekomstige minor versie (3.2)
- Issue lijst opbouwen
- Release elk kwartaal inplannen

Toekomstige major versie (4.0)
- Issue lijst opbouwen
- Release elk jaar inplannen

Versie creeeren:
- Changelog (wijzigingen van versie X naar versie X+1)
- Nieuwe versie OAS
- Nieuwe versie standaard.md
- Nieuwe versie opnemen in test platform
- Nieuwe Docker
- Nieuwe uitrol Docker naar gehoste versie test omgeving

**Comment by melsk-r** [comment]
@joeribekker en @michielverhoef (@TCIMEddy)
We hebben afgelopen maandag even bij elkaar gezeten om gezamenlijk het proces te schetsen wat doorlopen wordt om het beheer van een API standaard uit te voeren. Op basis waarvan ik mijn visie ga aanscherpen maar ook zeker om te bepalen over welke kennis we als API Beheerders moeten beschikken. Helaas is dat er deze week nog niet van gekomen. 

Wel heb ik op basis van de verworven inzichten het proces van het publiceren van een standaard en de gevolgen daarvan voor de provider en consumer leveranciers visueel gemaakt teneinde de gevolgen voor het releasebeleid duidelijk te krijgen.
Ik kom er nu achter dat ik dat spreadsheet ook aan GitGHub kan toevoegen, bij deze dus:
[Scenarios nightly builds 20181217.xlsx](https://github.com/VNG-Realisatie/api-beheer/files/2702868/Scenarios.nightly.builds.20181217.xlsx)

**Comment by melsk-r** [comment]
Michiel heeft daarop al de volgende opmerkingen gemaakt:

Het zijn meer dingen die me te binnen schoten toen ik het excel sheet doornam. Een beetje warrig wellicht maar gisteren bij de print demo kreeg ik weer eenzelfde gevoel als de laatste zin: een release candidate/vastgestelde versie van de standaard is “af” en eigenlijk komen alleen nog maar kritieke patches op. Geen nieuwe functionaliteit.
Je zegt dus eigenlijk dat er na de ontwikkeling van de API’s voor ZDS (ik neem ze nu voor het gemak maar even als 1 koppelvlak samen) er nooit een nieuwe versie van ZDS zal komen.
Ik kan het mis hebben maar dat lijkt mij sterk. Of wordt dat dan weer een nieuw ontwikkelproject?

Met de systeem API’s kun je natuurlijk alle resources van een API bewerken/bevragen etc. dus daar hoeft ook niets aangepast te worden, zolang het informatiemodel niet verandert. De enige API’s die relatief veel sneller kunnen veranderen zijn proces en met name experience API’s. Maar als we dat goed doen zijn het uitbreidingen op/toepassingen van de systeem API en zijn nieuwe functies aanvullingen en geen aapssingen van de systeem API.

We zouden zelfs kunnen zeggen dat we als standaard geen proces of experience API’s onderhouden maar alleen patronen, beschrijvingen hoe/met welke calls een zaakdocument toegevoegd kan worden (document toevoegen, relatie leggen in DRC, relatie leggen in ZRC, dat soort dingen).  Maar daar moeten we nog eens een ei over leggen.

Sheet versie 2.0.0:
Er staat beschreven dat consumer leveranciers 2 en 3  de standaard versie 2.0.0  niet implementeren omdat 1.1.0 beschikbaar blijft. 
Leverancier 3 blijft echter op versie 1.0.1 zitten. Dat mag, is een keuze maar dat is dan toch geen door VNG ondersteunde versie meer?

sheet versie 2.0.1:
Versie 2.0.1 staat in zwarte letters, de eerdere versies in rode letters (kolom links). Betekent dit dat de oudere versies niet meer ondersteund worden?

Wat ik nog lastig vind is wat te doen met oudere major versies? De reden om een major versie uit te brengen is een breaking change. Mag je van een provider verwachten dat deze beide versies blijft ondersteunen? Of mag een provider er voor kiezen om over te stappen op een nieuwe major versie en de oude versie niet meer te ondersteunen?

Helemaal in geval 5, waarbij een bug opgelost wordt. Die bug wil je niet meer in het systeem hebben.  Dus in de kolom productie provider zou ik verwachten dat daar vanaf periode 25 alleen nog versie 2.0.1 ondersteund wordt, misschien zelfs al vanaf periode 23.

Nog een vraag: Als het goed is 2.0.1 backwards compatible met 2.0.0 dus dan kan versie 2.0.0 van het lijstje ondersteunde versies. 

Wat in dit schema eigenlijk beschreven wordt is de ondersteuning van een API versie door de leverancier, niet door VNG. Eigenlijk moeten we dat los van elkaar zien, anders maken we het ons veel te moeilijk.

Als ik Hugo en Sergei gisteren goed begrepen heb blijft een API wanneer deze in gebruik is echt heel erg lang op één versie en zou het best eens kunnen zijn dat versie 2 helemaal niet of pas over jaren gaat komen.

Dan is het probleem misschien niet eens zo groot als we denken.

**Comment by melsk-r** [comment]
> 
> 
> **Aantekening beheer proces**
> 
> Legacy versie (1.1)
> Legacy versie (1.2)
> 
>     * Geen ondersteuning meer
> 
> 
> Deprecated versie (2.4)
> 
>     * Ondersteuning voor vragen
> 
>     * Ondersteuning in referentie implementatie
> 
>     * Alleen veiligheids issue kunnen zorgen voor een 2.5
> 
> 
> Huidig versie (3.1)
> 
>     * Ondersteuning voor vragen
> 
>     * Issues komen op de roadmap voor minor/major
> 
> 
> Toekomstige minor versie (3.2)
> 
>     * Issue lijst opbouwen
> 
>     * Release elk kwartaal inplannen
> 
> 
> Toekomstige major versie (4.0)
> 
>     * Issue lijst opbouwen
> 
>     * Release elk jaar inplannen
> 
> 
> **Versie creeeren:**
> Een major versie doorloopt typisch alpha, beta en release candidate (RC). Waarbij alpha versies nog in ontwikkeling zijn, beta is bijna gereed, en RC's zijn zo goed als af.
> 
>     * Changelog (wijzigingen van versie X naar versie X+1)
> 
>     * Nieuwe versie OAS
> 
>     * Nieuwe versie standaard.md
> 
>     * Nieuwe versie opnemen in test platform
> 
>     * Nieuwe Docker
> 
>     * Nieuwe uitrol Docker naar gehoste versie test omgeving
> 
> 
> **Onderhoud**
> Typisch leven er tegelijkertijd:
> 
>     * 2.4 (deprecated)
> 
>     * 3.1 (huidige versie)
> 
>     * 3.2-alpha (toekomstige versie)
> 
>     * 4.0-alpha (toekomstige versie)
> 
> 
> Versie 3.2 wordt op een gegeven moment 3.2-beta, en 3.2-RC. Zodra 3.2 gepubliceerd wordt dat de nieuwe huidige versie. Versie 3.1 vervalt eigenlijk. Dan leven er dus:
> 
>     * 2.4 (deprecated)
> 
>     * 3.2 (huidige versie)
> 
>     * 3.3-alpha (toekomstige versie)
> 
>     * 4.0-alpha (toekomstige versie)
> 
> 
> Versie 4.0-alpha wordt op een gegeven moment 4.0-beta, en 4.0-RC. Zodra 4.0 gepubliceerd wordt, wordt 3.1 deprecated en 2.4 wordt legacy. 3.3-alpha kan dan bijvoorbeeld vervallen (of niet). Dan leven er dus:
> 
>     * 3.2 (deprecated)
> 
>     * 4.0 (huidige versie)
> 
>     * 4.1-alpha (toekomstige versie)
> 
>     * 5.0-alpha (toekomstige versie)

@joeribekker Ik zie nu je bijdrage pas Joeri. Bedankt. Ik ga het bestuderen.

**Comment by michielverhoef** [comment]
Het W3C hanteert het volgende proces voor het beheer van hun standaarden: https://www.w3.org/2018/Process-20180201/ 

Als idee over hoe lang het duurt voordat er een nieuwe versie van een standaard uit is heb ik eens gekeken naar een standaard (recommendation) bij het W3C, de Web Content Accessibility Guidelines in dit geval.

De versiegeschiedenis van de huidige versie, 2.1 staat hier: https://www.w3.org/standards/history/WCAG21 
en de versiegeschiedenis van de hele standaard (alle versies): https://www.w3.org/standards/techs/wcag#w3c_all

Er zit 9 jaar tussen de versie 1.0 en 2.0 en bijna 10 jaar tussen 2.0 en 2.1. Ongetwijfeld zijn er tussendoor wat kleine dingen opgelost maar het laat goed zien dat een versie van een standaard ook echt af is (moet zijn) en dat zo'n versie dan echt lang mee gaat.

Het enige waar we nog echt een beeld bij moeten hebben is hoe lang leveranciers op een bepaalde versie van een standaard (mogen) blijven zitten. Als je kijkt naar de web standaarden, daar komt het voor (wel minder dan vroeger, maar nog steeds) dat men een verouderde browser (die oude versies van standaarden ondersteunt) gebruik (moet gebruiken). Alleen kan daar vrij makkelijk gezegd worden dat een deel van de website niet (goed) werkt.  Bij gemeenten is dat lastiger.

Zou er iets te af te dwingen zijn in bijvoorbeeld de Gibit dat in ieder geval een provider van een standaard binnen een bepaalde termijn de laatste versie van een standaard ingebouwd moet hebben? @hdksi?

**Comment by joeribekker** [comment]
Het W3C is wel een slecht voorbeeld. Het is ten eerste geen API en als je W3C als voorbeeld neemt, dan moet je ook naar alle problemen kijken. Zo zijn er juist omdat het W3C zo traag is allerlei browser specifieke elementen en attributen die er voor zorgen dat niet alle browsers hetzelfde laten zien en dat elke website rekening moet houden met alle browsers. Dit is juist wat we niet willen!

In 9 jaar tijd gebeurt veel, en je wil kunnen inspringen op deze ontwikkelingen.

Kijk liever naar de [Facebook API](https://developers.facebook.com/docs/graph-api/changelog/) (versie 3.2, 2 jaar support),[Microsoft REST/Graph API](https://docs.microsoft.com/en-us/graph/versioning-and-support) (2 jaar support, nu op versie 2) of [Google](https://cloud.google.com/apis/design/versioning) (Maps zit bijvoorbeeld op versie 3.35)

**Comment by joeribekker** [comment]
Braindump: Er moet ook een tabelletje komen met welke API versies met welke andere API versies compatible zijn. Flink wat werk, maar als we dat vanaf het begin goed doen is het erg fijn voor developers en beheerders. Het wordt wel een flinke graaf cuz everything is connected, yea!

Maar goed volgens mij is dat nu ook al zo alleen is het niet heel duidelijk dat RGBZ 2 werkt met RSGB 3 en ImZTC 2.1 en welke nog meer.

Zaken API | Besluiten API | Documenten API | Zaaktypen API | Opmerkingen
---|---|---|---|---
1.x | 1.x | 1.x | 1.x | Initiele release van de ZGW API's.
2.x | 2.x | 1.x | 1.x | Versie 2 van Zaken API heeft versie 2 van de Besluiten API nodig.

Is overigens een versie model waarbij je altijd alleen de laatste versie ondersteund maar je moet dan elke nieuwe versie backwards compatible maken.

Zie ook: https://nordicapis.com/api-change-strategy/

**Comment by melsk-r** [comment]
> 
> 
> Braindump: Er moet ook een tabelletje komen met welke API versies met welke andere API versies compatible zijn. Flink wat werk, maar als we dat vanaf het begin goed doen is het erg fijn voor developers en beheerders. Het wordt wel een flinke graaf cuz everything is connected, yea!
> 
> Maar goed volgens mij is dat nu ook al zo alleen is het niet heel duidelijk dat RGBZ 2 werkt met RSGB 3 en ImZTC 2.1 en welke nog meer.
> Zaken API 	Besluiten API 	Documenten API 	Zaaktypen API 	Opmerkingen
> 1.x 	1.x 	1.x 	1.x 	Initiele release van de ZGW API's.
> 2.x 	2.x 	1.x 	1.x 	Versie 2 van Zaken API heeft versie 2 van de Besluiten API nodig.
> 
> Is overigens een versie model waarbij je altijd alleen de laatste versie ondersteund maar je moet dan elke nieuwe versie backwards compatible maken.
> 
> Zie ook: https://nordicapis.com/api-change-strategy/

@joeribekker: Ik denk dat het verstandiger is om dit lijstje per standaard te verstrekken dan het voor alle standaarden te consolideren. Dit moet opgenomen worden in de lijst met criteria voor het in beheer nemen van een standaard. Dat betekent dus dat de ZGW standaarden dit straks al moeten bevatten als deze in beheer genomen moeten worden. Heb je hiervoor daarom bij ZGW ook al een userstory aangemaakt?

**Comment by TCIMEddy** [comment]
Ik zet deze user story op close/done. Ik besef me terdege dat hier nog veel tijd aan besteed moet worden. Graag alleen user stories opvoeren die concrete actie vereisen (bijvoorbeeld cursus volgen...). Dus nogmaals kennis opdoen is on the job!! en belangrijk
