### ISSUE TITLE
Als beheerder wil ik dat de nog niet gerealiseerde backlog van een nieuwe standaard overgedragen wordt aan beheer

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/api-beheer#38]
zodat deze wensen en eisen voor de roadmap/doorontwikkeling niet verloren gaan

**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg voor een sprint
- [x] Product Owner akkoord en voorzien van prio
- [x] Voorzien van Acceptatiecriteria
- [x] Voorzien van Definition of Done
- [x] Voorzien van taken
- [x] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

- [ ] Er is een procedure voor gedocumenteerd in markdown op GitHub.

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [ ] Het is duidelijk wat er gebeurt met deze User Stories.
- [ ] Backlog blijft waar hij is. Het is niet de bedoeling om de issues in de backlog naar een andere backlog over te hevelen. Geef de beheerder(s) echter de gelegenheid om vragen te stellen en om zo nodig kennis te maken met de ontwikkelaar(s) van de standaard.

**Acceptatiecriteria**

- [ ] Niet belemmerend werken voor beheer andere standaarden
- [ ] Procedure is eenduidig.

**Taken**

- [x] Procedure opstellen

**Comment by melsk-r** [comment]
@michielverhoef, @joeribekker, @TCIMEddy  In [beheer.md](https://github.com/VNG-Realisatie/api-beheer/blob/master/beheer.md) heb ik de procedure verwerkt. Graag nagaan of dit voldoende is.

**Comment by TCIMEddy** [comment]
@melsk-r Ziet er goed uit. In het vervolg kun je verplichte reviewers aangeven via een pr dan weet je zeker dat mensen formeel akkoord geven

**Comment by michielverhoef** [comment]
Volgens mij is de beschrijving in beheer.md voorlopig voldoende. Heel spannend is het ook niet natuurlijk.

**Comment by joeribekker** [comment]
Voor mijn begrip, dit ticket gaat dus over deze toevoeging: https://github.com/VNG-Realisatie/api-beheer/commit/3a8bf4e2bcdd0bbd5bddb33d9b8d60ecd1e1c07a#diff-43efbdde6b5ffdd46c3d10b53dbe19c6

Ik zou nog wel toevoegen: Zorgen dat de repository volgens VNG standaard is.
Hierbij stel ik me zo voor dat:

- De README volgens VNG standaard is (zie bijv. [hier](https://github.com/maykinmedia/demo-api))
- De ISSUE/PR templates een vast stramien hebben (zie bijv. [hier](https://github.com/VNG-Realisatie/api-beheer/tree/master/.github/ISSUE_TEMPLATE))

Ook stel ik me voor dat er minimaal 2 repo's zijn:

1) De referentie implementatie
2) De OAS

Het moet dan duidelijk zijn in welke repo, welke vragen kunnen worden gesteld en/of issues worden aangemaakt.

**Comment by michielverhoef** [comment]
Omdat de versie van de referentie implementatie 1 op 1 samen moet lopen (referentie implementatie is onderdeel van de standaard) met die van de OAS, is het niet veel handiger om alles in 1 repository op te nemen en te beheren?  Dan is ook duidelijk waar vragen over de standaard (inclusief referentie implementatie) gesteld kunnen worden.

**Comment by melsk-r** [comment]
@joeribekker  kan jij reageren op de vraag van Michiel of het niet handiger is om slechts 1 repo te hanteren. Ik neem aan dat jij redenen hebt om er juist 2 te hebben.

**Comment by michielverhoef** [comment]
Vanuit de ZGW standaard begrijp ik het wel, dat is een standaard die bestaat uit meerdere referentie componenten. Dan wordt het al snel heel erg onoverzichtelijk en onbeheer(s)baar wanneer alles in 1 grote repository zit.

**Comment by joeribekker** [comment]
> Omdat de versie van de referentie implementatie 1 op 1 samen moet lopen (referentie implementatie is onderdeel van de standaard) met die van de OAS, is het niet veel handiger om alles in 1 repository op te nemen en te beheren? Dan is ook duidelijk waar vragen over de standaard (inclusief referentie implementatie) gesteld kunnen worden.

Ik verwijs toch even naar de Demo API die ik heb opgesteld:

* https://github.com/maykinmedia/demo-api-component
* https://github.com/maykinmedia/demo-api

Er is een repository voor de code (`demo-api-component`) en voor de OAS (`demo-api`). Ik vind dit zelf wel netjes om het gescheiden te houden, anders lopen alle commits door elkaar heen. Als je voor deze repositories goede naamgeving vind, is het ook fijn te onderhouden ipv dat zooitje wat het nu wordt... Het kan overigens wel in 1 repository.

Ik zie voor me dat er een website komt die orde schept, 1 pagina per API-collectie met daaronder de API's, en daaronder de documentatie, referentie implementatie, OAS, client libraries, etc.

**ZGW**
- Zaken API
  - Documentatie
  - Specificatie
  - Referentie implementatie
  - Client bibliotheken
- Catalogus API
  - Documentatie
  - Specificatie
  - Referentie implementatie
  - Client bibliotheken

**Basisregistreaties**
- Personen API
  - Documentatie
  - Specificatie
  - Referentie implementatie
  - Client bibliotheken
- Kadaster API
  - Documentatie
  - Specificatie
  - Referentie implementatie
  - Client bibliotheken

**Comment by melsk-r** [comment]
> 
> 
> Voor mijn begrip, dit ticket gaat dus over deze toevoeging: [3a8bf4e#diff-43efbdde6b5ffdd46c3d10b53dbe19c6](https://github.com/VNG-Realisatie/api-beheer/commit/3a8bf4e2bcdd0bbd5bddb33d9b8d60ecd1e1c07a#diff-43efbdde6b5ffdd46c3d10b53dbe19c6)
> 
> Ik zou nog wel toevoegen: Zorgen dat de repository volgens VNG standaard is.
> Hierbij stel ik me zo voor dat:
> 
>     * De README volgens VNG standaard is (zie bijv. [hier](https://github.com/maykinmedia/demo-api))
> 
>     * De ISSUE/PR templates een vast stramien hebben (zie bijv. [hier](https://github.com/VNG-Realisatie/api-beheer/tree/master/.github/ISSUE_TEMPLATE))
> 
> 
> Ook stel ik me voor dat er minimaal 2 repo's zijn:
> 
>     1. De referentie implementatie
> 
>     2. De OAS
> 
> 
> Het moet dan duidelijk zijn in welke repo, welke vragen kunnen worden gesteld en/of issues worden aangemaakt.

Ik denk dat dit veel meer thuis hoort bij issue #46. Dit gaat immers niet over het overdragen van de backlog maar over de eisen die wij stellen aan de structuur van een GitHub repository.

**Comment by melsk-r** [comment]
@joeribekker, @michielverhoef  Alleen jullie akkoord. Daarna sluit ik dit issue.
