### ISSUE TITLE
Als beheerder wil ik updates kunnen uitvoeren op de referentie-implementaties

### ISSUE THREAD

**Issue by wishalg** [VNG-Realisatie/api-beheer#4]
zodat deze in lijn blijft lopen met de OAS3 specificatie zodra deze wijzigt,

Lijkt erg op #57. Volgende sprint kijken wat er nog openstaat in deze User Story
**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg voor een sprint
- [x] Product Owner akkoord en voorzien van prio
- [x] Voorzien van Acceptatiecriteria
- [x] Voorzien van Definition of Done
- [x] Voorzien van taken
- [x] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [ ] ontwikkelomgeving moet beschikbaar zijn op laptop/desktop;

Toekomstige beheerders moeten beschikken over:
- [ ] vaardigheden voor het zelf opzetten van de ontwikkelomgeving;
- [ ] vaardigheden voor het uitvoeren van updates;
- [ ] vaardigheden voor het uitrollen van een nieuwe versie van de referentie-implementaties;
- [ ] vaardigheden voor het opnieuw kunnen genereren van de OAS3 specificaties;
- [ ] autorisatierechten binnen de beheeromgeving voor het kunnen uitvoeren van de updates.
- [ ] ...

**Acceptatiecriteria**

- [ ] Niet belemmerend werken voor beheer andere standaarden
- [ ] ...
- [ ] ...
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**

- [ ] Regelen autorisaties. (@...)
- [ ] Regelen benodigde software en evt. licenties. (@...)
- [ ] Opzetten traject voor kennisoverdracht (workshop, cursus, zelf-leertraject, ...) (@...)
- [ ] .... (@...)

**Comment by michielverhoef** [comment]
Naar aanleiding van de doelen onder het kopje specifiek zijn de volgende user stories aangemaakt:
#55 ,  #56 ,  #57 ,  #58 , #59

**Comment by TCIMEddy** [comment]
@melsk-r Ik heb deze in de review kolom geplaatst wat mij betreft ready en op jouw naam gezet om indien akkoord te slepen naar ready for sprint (en dan mag je je naam er weer vanaf halen)

**Comment by melsk-r** [comment]
Ik wil eerst duidelijkheid hebben OF wij als beheerders wel wijzigingen gaan aanbrengen aan referentie implementaties. Zo niet of nog niet dan hoeven we hier (nu) geen tijd in te steken.

**Comment by TCIMEddy** [comment]
@melsk-r Juiste toepassing van prioriteren!! Lijkt me wel goed om de vraag dan als user story op te nemen en die dan te (laten) beantwoorden.

**Comment by melsk-r** [comment]
Zie #71

**Comment by TCIMEddy** [comment]
@michielverhoef @melsk-r @joeribekker Ik heb deze op close gezet aangezien deze eigenlijk hetzelfde is met #57 (deze zit in de huidige sprint). Indien niet akkoord graag melding!
