### ISSUE TITLE
Als beheerder wil ik een overzicht van de benodigde software incl. eventuele licenties.

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/api-beheer#44]
...zodat:
- duidelijk is welke software geïnstalleerd moet worden;
- duidelijk is of er voor alle software licenties zijn;
- bijgehouden kan worden wie welke software/licentie in gebruik heeft.

**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg voor een sprint
- [x] Product Owner akkoord en voorzien van prio
- [x] Voorzien van Acceptatiecriteria
- [x] Voorzien van Definition of Done
- [x] Voorzien van taken
- [x] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [ ] Er wordt een lijst met benodigde software opgesteld;
- [ ] Bij elke software wordt vastgelegd of licenties noodzakelijk zijn en zo ja wat die licenties zijn als ze al voorhanden zijn;
- [ ] Er wordt vastgelegd welke licentie bij wie geïnstalleerd is/gaat worden;
- [ ] ...

**Oplossingsrichting**

...

**Acceptatiecriteria**

- [ ] Niet belemmerend werken voor beheer andere standaarden
- [ ] Er is een lijst met benodigde software;
- [ ] Bij elke software is vastgelegd of licenties noodzakelijk zijn en zo ja wat die licenties zijn indien ze al aanwezig zijn;
- [ ] Er is vastgelegd welke licentie bij wie geïnstalleerd is/gaat worden;
- [ ] Er kan bepaald worden welke licenties besteld moeten worden;
- [ ] ...

**Taken**

- [ ] Inventariseer samen met @joeribekker de benodigde software (@...)
- [ ] Bepaal voor welke software een licentie nodig is en inventariseer evt. licenties (@...)

**Comment by TCIMEddy** [comment]
@melsk-r waar is deze duplicaat van? En kan ik deze dan 'close'?

**Comment by melsk-r** [comment]
Er is geen duplicaat van dit issue. Dit moet openblijven.
