### ISSUE TITLE
Als beheerder wil ik over de benodigde software (met evt. licenties) kunnen beschikken.

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/api-beheer#45]
Zodat ik het beheerwerk ook echt kan uitvoeren.

**Definition of ready**

- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg voor een sprint
- [ ] Product Owner akkoord en voorzien van prio
- [ ] Voorzien van Acceptatiecriteria
- [ ] Voorzien van Definition of Done
- [ ] Voorzien van taken
- [ ] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [ ] Benodigde software of een link naar waar deze kan worden gedownload is aanwezig.
- [ ] Van de software waarvoor licenties noodzakelijk zijn zijn licenties voor alle beheerders aanwezig.

**Acceptatiecriteria**

- [ ] Niet belemmerend werken voor beheer andere standaarden
- [ ] Er is een lijst van de benodigde software, waar deze verkregen kan worden en hoe deze geïnstalleerd moet worden in het geval daar speciale handelingen voor nodig zijn
- [ ] De software kan bij wijze van spreken direct geïnstalleerd worden.

**Taken**

- [ ] Inventarisatie van de benodigde software. (@joeribekker)
- [ ] Bestellen van de benodigde licenties. (@...)
- [ ]

**Comment by TCIMEddy** [comment]
Dubbel dus close
