### ISSUE TITLE
Als beheerder wil ik duidelijkheid over de eisen waaraan een over te dragen standaard moet voldoen.

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/api-beheer#46]
...zodat:
* een ontwikkelteam vooraf weet waaraan het toe is en weet waarin het moet voorzien.
* er daarover geen discussie kan ontstaan bij overdracht van een standaard van ontwikkeling naar beheer.

**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg voor een sprint
- [x] Product Owner akkoord en voorzien van prio
- [x] Voorzien van Acceptatiecriteria
- [x] Voorzien van Definition of Done
- [x] Voorzien van taken
- [x] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [x] Alle eisen waaraan een standaard moet voldoen voordat tot overdracht kan worden overgegaan moeten worden vastgelegd
- [x] Indien er situaties zijn waarin niet aan een eis kan worden voldaan dan moet dat per eis worden vastgelegd zodat een ontwikkelteam zich er op kan beroepen.

**Oplossingsrichting**

...

**Acceptatiecriteria**

- [x] Niet belemmerend werken voor beheer andere standaarden
- [ ] ...

**Taken**

- [x] Stel een lijst met eisen op. (@...)
- [x] Bepaal per eis of er situaties zijn waarin niet aan die eis hoeft te worden voldaan. (@...)

**Comment by melsk-r** [comment]
Bij deze alvast een eerste lijst zodat ik ze iig ergens heb opgeslagen:
API specificatie (OAS3) moet beschikbaar zijn
Documentatie (zowel technisch als functioneel) moet beschikbaar zijn
De referentie-implementatie (provider) moet gereed zijn
Demo applicatie (consumer) moet beschikbaar zijn
Er moet een informatiemodel zijn
Geautomatiseerde test en buildstraat (CI) moet beschikbaar zijn
De standaard moet ingebouwd zijn bij leveranciers
De standaard bevat een tabel waarin wordt aangegeven welke API versies met welke andere API versies compatible zijn.

**Comment by melsk-r** [comment]
Ik denk dat het handig is als we deze userstory in de volgende sprint meenemen.
Hier moeten we n.m.m. vlug wat meer inzicht in verkrijgen zodat we daar met het oog op potentieel in beheer te nemen standaarden al op kunnen sturen. Ik zal hem dus in de 'Ready Maken' kolom plaatsen.

**Comment by TCIMEddy** [comment]
@melsk-r heldere lijst. Kun je IM specificeren zodat iedereen hierover eenduidig begrip heeft. en standaard moet ingebouwd zijn... bij iedereen, bij 1 bij de meerderheid. Rest kraakhelder

**Comment by joeribekker** [comment]
Zie #90

**Comment by joeribekker** [comment]
Ik ga em iets concreter maken vanuit #8: https://github.com/VNG-Realisatie/api-beheer/issues/8#issuecomment-467383867

**Comment by TCIMEddy** [comment]
@melsk-r volgens mij kun je deze op done zetten en eventuele toekomstige wijzigingen voeren we door. Maar wat mij betreft geen aparte user story meer

**Comment by melsk-r** [comment]
Ik zal hem sluiten. Wijzigingen zullen er idd vast komen.
