### ISSUE TITLE
Presentatie sprint 0 maken

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-beheer#51]
[Scrum Beheer v1.1.pptx](https://github.com/VNG-Realisatie/api-beheer/files/2638458/Scrum.Beheer.v1.1.pptx)

**Comment by TCIMEddy** [comment]
@joeribekker @wishalg @michielverhoef @melsk-r Beetje laat... dus wellicht ben ik zaken vergeten of verkeerd weergegeven. Graag review en commentaren via comments dan pas ik het aan.

**Comment by joeribekker** [comment]
Ziet er goed uit en zoals besproken.
Jammer dat uren PO niet zijn ingevuld ;-)

Je herinnert ook aan 7 december dus nog best werk te doen.

**Comment by michielverhoef** [comment]
Een paar kleine typefouten op sheet 8:
![afbeelding](https://user-images.githubusercontent.com/34736717/49365454-285f1b80-f6e7-11e8-96be-06091b647182.png)

**Comment by melsk-r** [comment]
Ik kan me vergissen maar ik dacht dat we ook 29 maart als voorlopige einddatum hadden afgesproken. 
Ik heb in mijn notities i.i.g. de volgende data staan:
* 7 december start sprint 1
* 4 januari start sprint 2
* 1 februari start sprint 3
* 1 maart start sprint 4
* 29 maart eind sprint 4

Verder lijkt het me allemaal in orde.

**Comment by wishalg** [comment]
Idem, ziet er goed

**Comment by TCIMEddy** [comment]
Dank voor alle input en verwerkt in v1.2
