### ISSUE TITLE
Als beheerder wil ik de vaardigheden voor het uitvoeren van updates aan de referente implementatie beheersen

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/api-beheer#56]
...zodat ik een update aan de referentie implementatie (fix of doorontwikkeling) uit kan voeren.

**Definition of ready**

- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg voor een sprint
- [ ] Product Owner akkoord en voorzien van prio
- [ ] Voorzien van Acceptatiecriteria
- [ ] Voorzien van Definition of Done
- [ ] Voorzien van taken
- [ ] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**
- [ ] contactgegevens van partijen (hosting, ontwikkelaars referentie implementatie) om eventueel een actie uit te kunnen voeren die beheer niet zelf kan.
- [ ] kennis van de noodzakelijke stappen (Beschrijving van de werkzaamheden die noodzakelijk zijn om een update uit te voeren)
- [ ] beschikking over de noodzakelijke software

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [ ] ...
- [ ] ...

**Oplossingsrichting**

...

**Acceptatiecriteria**

- [ ] Niet belemmerend werken voor beheer andere standaarden
- [ ] ...

**Taken**

- [ ] ... (@...)
- [ ] ... (@...)

**Comment by TCIMEddy** [comment]
@melsk-r In zet het in de sprint. Concrete acties moeten nog geformuleerd worden. Dus ook nog niet in beton wie of wat?

**Comment by TCIMEddy** [comment]
Close conform stand-up
