### ISSUE TITLE
Als beheerder wil ik weten hoe ik een OAS3 specificatie opnieuw kan genereren;

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/api-beheer#58]
...zodat na een aanpassing in de referentie implementatie de OAS specificatie bijgewerkt kan worden.

**Definition of ready**

- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg voor een sprint
- [ ] Product Owner akkoord en voorzien van prio
- [ ] Voorzien van Acceptatiecriteria
- [ ] Voorzien van Definition of Done
- [ ] Voorzien van taken
- [ ] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**
- [ ] beschrijving werkwijze (howto)
- [ ] beschikbaarheid tooling
- [ ] 

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [ ] ...
- [ ] ...

**Oplossingsrichting**

...

**Acceptatiecriteria**

- [ ] Niet belemmerend werken voor beheer andere standaarden
- [ ] ...

**Taken**

- [ ] ... (@...)
- [ ] ... (@...)

**Comment by melsk-r** [comment]
@TCIMEddy Waarom was hier het Impedement label ook al weer aan gekoppeld?

**Comment by TCIMEddy** [comment]
@melsk-r Of het genereren altijd vanuit de imvertor moet. Er is volgens mij nog discussie over. Wat verwacht je overigens van mij hierin?

**Comment by melsk-r** [comment]
@TCIMEddy Voorlopig even niets. Kom ik op terug.

**Comment by TCIMEddy** [comment]
Discussie lopen nog -> dus in afwachting hiervan, geen impediment

**Comment by joeribekker** [comment]
Denk ook dat dit overgelaten moet worden aan API developers en/of API designers, en niet direct door beheer.

**Comment by TCIMEddy** [comment]
Ik close deze user story aangezien er is besloten om de methodiek van de in beheer te nemen API te volgen.
