### ISSUE TITLE
Als beheerder wil ik beschikken over de juiste autorisatierechten binnen de beheeromgeving

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/api-beheer#59]
...zodat de updates kan uitvoeren.

**Definition of ready**

- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg voor een sprint
- [ ] Product Owner akkoord en voorzien van prio
- [ ] Voorzien van Acceptatiecriteria
- [ ] Voorzien van Definition of Done
- [ ] Voorzien van taken
- [ ] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [ ] Opstellen van een lijst met rechten die beheerders nodig hebben om het beheer uit te kunnen voeren.
- [ ] Bepalen of rechten worden toegekend aan alle beheerders of dat per project de rechten worden bepaald.
- [ ] Het toekennen van rechten aan de betreffende beheerder.

**Oplossingsrichting**

...

**Acceptatiecriteria**

- [ ] Niet belemmerend werken voor beheer andere standaarden
- [ ] Het is bekend welke rechten beheerders nodig hebben om het beheer uit te kunnen voeren.
- [ ] Er is een besluit of alle beheerders dezelfde rechten krijgen op alle beheerprojecten of dat dit per project wordt bepaald.
- [ ] De juiste rechten zijn toegekend aan de betreffende beheerder(s).

**Taken**

- [ ] ... (@...)
- [ ] ... (@...)

**Comment by TCIMEddy** [comment]
@kciredor @wishalg Dit is een behoefte uit dit team. Hoe ziet de beheeromgeving eruit om al die standaarden en bijbehorende referentie-implementaties te beheren. Komen waarschijnlijk nog veel meer bij kijken maar is niet aan dit team om het op te lossen. Komt dit overeen met jullie beeld? Wij closen dit soort user stories bij ons op het bord en wijzen ze ter info toe aan @kciredor
