### ISSUE TITLE
Als beheerder wil ik weten hoe ik met Jenkins moet werken

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/api-beheer#60]
...zodat ik de continuous integration straat kan besturen.

**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg voor een sprint
- [x] Product Owner akkoord en voorzien van prio
- [x] Voorzien van Acceptatiecriteria
- [x] Voorzien van Definition of Done
- [x] Voorzien van taken
- [ ] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [ ] Maak duidelijk OF Jenkins bij het beheer van standaarden wordt gebruikt en of dat door de beheerders wordt gebruikt.
- [ ] Zo ja, maak duidelijk waar en hoe Jenkins bij het beheer van standaarden wordt gebruikt
- [ ] Kennisvergaring m.b.t. Jenkins
- [ ] ...

**Oplossingsrichting**

...

**Acceptatiecriteria**

- [ ] Niet belemmerend werken voor beheer andere standaarden
- [ ] Het is duidelijk waar en waarvoor Jenkins wordt gebruikt;
- [ ] Jenkins kan aantoonbaar worden toegepast.

**Taken**

- [ ] Inzicht geven in de positionering van Jenkins. (@joeribekker )
- [ ] Bepalen van de juiste wijze van kennisvergaring (@joeribekker, @michielverhoef , @melsk-r)
- [ ] Vergaren van kennis (@michielverhoef , @melsk-r )

**Comment by TCIMEddy** [comment]
@kciredor wellicht heb jij hier ideeën bij.

**Comment by melsk-r** [comment]
Ik heb de prio er even af gehaald aangezien mij niet duidelijk is of wij hier op korte termijn mee aan de gang moeten. Het zou fijn zijn als @kciredor hier wat licht in de duisternis kan scheppen.

**Comment by kciredor** [comment]
Vermoedelijk raakt dit niet beheer, aangezien je docker containers kant en klaar aangeleverd krijgt (en dus geen Jenkins CI/CD pipeline nodig hebt om tot een docker build te komen). Volgens mij kun je deze sluiten.

**Comment by melsk-r** [comment]
Dan sluit ik hem bij deze.
