### ISSUE TITLE
Als beheerder heb ik kennis van Python

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/api-beheer#62]
...zodat ik in staat ben om de referentie implementatie aan te passen.

**Definition of ready**

- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg voor een sprint
- [ ] Product Owner akkoord en voorzien van prio
- [ ] Voorzien van Acceptatiecriteria
- [ ] Voorzien van Definition of Done
- [ ] Voorzien van taken
- [ ] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [ ] Het opbouwen van Python kennis.
- [ ] ...

**Oplossingsrichting**

* Workshop/Cursus
* 'On the job' kennisoverdracht
* Zelfstudie
* Combinatie van een of meer van de bovenstaande opties

**Acceptatiecriteria**

- [ ] Niet belemmerend werken voor beheer andere standaarden
- [ ] De beheerder is aantoonbaar in staat om wijzigingen aan te brengen aan de referentie implementatie (of een testvariant daarvan).

**Taken**

- [ ] Bepalen van de meest geschikte wijze waarop Python kennis kan worden opgedaan
- [ ] Afhankelijk van de gekozen route volgen van een workshop/cursus of doen van zelfstudie;
- [ ] 'On the job' kennisoverdracht;
- [ ] Vergaren van kennis (@michielverhoef , @melsk-r )

**Comment by TCIMEddy** [comment]
@melsk-r Wat mij betreft op close!? Is zinvol maar geen aparte user story

**Comment by michielverhoef** [comment]
Volgens mij is Python kennis 1 ding maar minstens zo belangrijk is kennis en ervaring met de tooling om van een stukje Python code een werkende RI te kunnen maken (MVC framework, Kubernetes, een RI verpakken in een Docker container etc.).

Gezien de eerste insteek om de leverancier van de RI ook het onderhoud te laten verzorgen zou ik zeggen sluiten.
