### ISSUE TITLE
Er moet een test ontwikkelomgeving ingericht worden zodat we de noodzakelijke vaardigheden kunnen uitproberen.

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/api-beheer#63]
We willen omgeving waarin we de vaardigheden die we moeten opdoen kunnen uitproberen zodat we er handigheid in kunnen krijgen. Dit mag ergens centraal zijn of bij de beheerder(s) lokaal zolang we maar dit maar niet in productieomgevingen hoeven te doen.

**Comment by TCIMEddy** [comment]
@melsk-r @michielverhoef Moet ik hier nog iets aan doen?

**Comment by ehotting** [comment]
Ben bezig om "ops" voor alle teams centraal te regelen zodat je eenvoudig beschikking kunt krijgen over omgevingen.

**Comment by michielverhoef** [comment]
Klinkt goed maar het lijkt me wel handig om beheer dingen tussen de PO's onderling af te stemmen zodat we niet min of meer hetzelfde (maar dan net even anders) gaan regelen.

**Comment by TCIMEddy** [comment]
@wishalg Jij organiseert PO-overleg. Moet Eelco of meerdere mensen nog aanhaken?

**Comment by TCIMEddy** [comment]
@wishalg kun jij hier ook even naar kijken ivm komst Roderick

**Comment by melsk-r** [comment]
@kciredor uiteindelijk wil ik in deze omgeving het gehele beheerproces kunnen doorlopen voor de demo applicatie. Kunnen we dat probleemloos dan denk ik dat we kunnen zeggen dat we wat dat betreft klaar zijn voor het in beheer nemen van een API standaard.

**Comment by kciredor** [comment]
Ter referentie zie ook #102

**Comment by kciredor** [comment]
Zojuist offline besproken.

Voor nu lever ik vanuit "Haven" een of meer vm's met docker aan, om in ieder geval alvast te kunnen bewegen.

Vooruitlopend op de engineering van "Haven", waarbij Kubernetes in beeld komt.

**Comment by kciredor** [comment]
Docker vm's zojuist opgeleverd.

**Comment by melsk-r** [comment]
Ik vermoed dat dit issue op Done gezet kan worden.
@kciredor heeft een VM opgeleverd die ik en volgens mij ook @michielverhoef gebruiken om met Docker te kunnen testen.

**Comment by kciredor** [comment]
Eens, wat mij betreft done.
