### ISSUE TITLE
Als leverancier wil ik op slack vragen kunnen stellen aan VNG en/of andere leveranciers

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/api-beheer#64]
...zodat ik veel directer vragen kan stellen en antwoorden kan vragen.

**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg voor een sprint
- [x] Product Owner akkoord en voorzien van prio
- [x] Voorzien van Acceptatiecriteria
- [x] Voorzien van Definition of Done
- [x] Voorzien van taken
- [x] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Oplossingsrichting**

1 Slack, per API een channel

**Acceptatiecriteria**

- [x] Niet belemmerend werken voor beheer andere standaarden
- [ ] ...

**Taken**

- [x] Slack opstarten
- [x] Kanalen aanmaken
- [x] VNG mensen uitnodigen op Slack
- [x] Slack kanaal publiceren ergens (@michielverhoef)
- [x] Procedure m.b.t. Slack channel vastleggen (@melsk-r)

**Comment by michielverhoef** [comment]
https://join.slack.com/t/vngapicommunity/shared_invite/enQtNDk1OTg5ODYwNjc1LTc0NTAxYWUzMGJmYjIxODQ2MGJmNDA4ZDk2YjNmNzI5NzU1MjAwMjllMTIwYjgxMjg1M2U0Zjg5N2QyOTkzZjI

**Comment by michielverhoef** [comment]
Een [slack workgroup](https://join.slack.com/t/vngapicommunity/shared_invite/enQtNDk1OTg5ODYwNjc1LTc0NTAxYWUzMGJmYjIxODQ2MGJmNDA4ZDk2YjNmNzI5NzU1MjAwMjllMTIwYjgxMjg1M2U0Zjg5N2QyOTkzZjI) is aangemaakt.

**Comment by michielverhoef** [comment]
Alle deelnemers zijn uitgenodigd, een groot deel is al aangehaakt.
Volgens mij kan dit issue gesloten worden.

**Comment by joeribekker** [comment]
Zeer pro actief!

Hopelijk is de PO akkoord ;-)

**Comment by melsk-r** [comment]
Inderdaad heel pro actief.
In principe keur ik hem goed al heb ik nog wel wat vraagjes.

1. is dit een kanaal waar algemene vragen gesteld kunnen worden?
2. is dit een kanaal waar vragen over het nieuwe Open API ZDS koppelvlak gesteld kunnen worden?
3. of is dit een kanaal waar allerlei vragen gesteld kunnen worden?

In dat laatste geval hou ik er rekening mee dat er vragen gesteld gaan worden die niet meteen in de juiste context geplaatst kunnen worden. Vragen waarvan je niet meteen weet over welk koppelvlak het gaat. In dat geval is het misschien handig om per koppelvlak een channel aan te maken en een general channel voor algemene vragen.

Het sluiten van dit issue is n.m.m. overigens wat te snel gebeurd.
Ten eerste omdat ik er nog niet eens een prio aan toegekend heb en ik hem niet officieel heb goedgekeurd maar nog belangrijker omdat er nog 1 taak openstaat, het publiceren van het slack kanaal.
Heeft daar iemand ideeën bij?

**Comment by melsk-r** [comment]
Ik zie zojuist dat het ook de bedoeling is om per API een channel te openen. Dus die vraag is beantwoord.

**Comment by TCIMEddy** [comment]
@melsk-r Top! zo scherp moet je zijn als PO. Hij is idd te snel op done gezet. Zo moeten we het 'scrum-spel' met elkaar gaan spelen.

**Comment by michielverhoef** [comment]
Het slack kanaal is ook al gepubliceerd: er is een mail naar de deelnemers van het API Lab met daarin de uitnodigingslink verstuurd. Als je kijkt in het kanaal "slackbot" zie je wie zich wanneer aangemeld heeft.

We zouden nog op het aloude KING discussieforum kunnen posten en een verwijzing kunnen maken op GEMMA Online?

**Comment by melsk-r** [comment]
Ik vrees dat alleen jij als creator van de slack community in het kanaal slackbot kan zien wie zich aangemeld hebben. Bij mij is deze nagenoeg leeg. We kunnen natuurlijk iets op de fora plaatsen (k zou het dan op meerdere fora doen trouwens) en op GEMMA Online maar ik weet niet of we daar de complete doelgroep mee kunnen bereiken. Dat zal met de mail naar de deelnemers van de API Lab ook niet gebeurd zijn. Iemand ideeen over kanalen waar we hier ruchtbaarheid aan kunnen geven?

Ben je het er trouwens mee eens dat we straks per koppelvlak een channel moet aanmaken?
Zo ja moeten we dat dan niet alvast doen voor de koppelvlakken waaraan nu gewerkt wordt of doen we dat pas als we ze in beheer nemen. In dat laatste geval moeten we misschien nog even wachten met ruchtbaarheid geven aan deze slack community.

**Comment by michielverhoef** [comment]
Vreemd want ik heb jou workspace owner gemaakt dus ik zou verwachten dat jij ook alles ziet en mag?

In het kader van devops zou ik zeggen dat we met de start van de ontwikkeling van een koppelvlak een channel aanmaken. Alleen is even de vraag: wat is een koppelvlak? Voor mij is een koppelvlak de API aangeboden door een referentiecomponent, bijvoorbeeld de ZRC of de DRC.  Dus de ZRC API is een ander koppelvlak dan de DRC API.

Mocht een component ook in een andere combinatie gebruikt worden, bijvoorbeeld omdat een DRC ook in een andere context dan zaakgericht werken gebruikt gaat worden, is het belangrijk dat discussies voor de API van dat component ook gezien worden door andere gebruikers zodat zij in kunnen schatten wat eventuele gevolgen van aanpassingen ed. kunnen zijn.

Een koppelvlak als Bevragen Ingeschreven Personen is eigenlijk ook API geboden door 1 referentie component dus dat krijgt ook een eigen channel.
Denk ik dan.

**Comment by michielverhoef** [comment]
Voor de reclame: als we in ieder geval elk koppelvlak de eigen doelgroep (werkgroep/verzendlijst) op de hoogte laten stellen dan zijn in ieder geval die partijen op de hoogte.

Dit is denk ik ook iets wat moet groeien dus we moeten het in zoveel mogelijk communicatie (mailings etc.) meenemen/noemen. Hopelijk wijzen leveranciers en gemeenten elkaar dan ook op het bestaan van deze slack workgroup en bereiken we zo nog meer partijen.

**Comment by ehotting** [comment]
> Ik vrees dat alleen jij als creator van de slack community in het kanaal slackbot kan zien wie zich aangemeld hebben. Bij mij is deze nagenoeg leeg. 

De inhoud van het Slackbot channel is afhankelijk van wat je zelf doet, voor ieder individueel

**Comment by melsk-r** [comment]
> > Ik vrees dat alleen jij als creator van de slack community in het kanaal slackbot kan zien wie zich aangemeld hebben. Bij mij is deze nagenoeg leeg.
> 
> De inhoud van het Slackbot channel is afhankelijk van wat je zelf doet, voor ieder individueel

Vreemd dan dat Michiel wel ziet wie zich aangemeld heeft. Michiel heeft immers een mail gestuurd en niet de betreffende mensen uitgenodigd via Slack.

**Comment by melsk-r** [comment]
In de takenlijst staat:

> VNG mensen uitnodigen op Slack

Moeten leveranciers echter niet ook uitgenodigd worden?

**Comment by TCIMEddy** [comment]
@melsk-r Dat lijkt me wel toch

**Comment by melsk-r** [comment]
> 
> 
> @melsk-r Dat lijkt me wel toch

Michiel heeft bevestigd dat dit ook gebeurd is. Leveranciers kunnen zichzelf aanmelden en dat wordt ook al gedaan.

Ik heb in het bestaande PR op beheer.md nu ook een sectie opgenomen met daarin een beschrijving hoe om te gaan met Slack.

**Comment by michielverhoef** [comment]
Zojuist ook nog een post aangemaakt op het discussieforum: https://discussie.kinggemeenten.nl/discussie/gemma/koppelvlak-zs-dms/slack-discussiegroep-voor-ontwikkeling-apis 

Wat mij betreft is met de verschillende berichtgevingen en uitnodigingen het slack kanaal ruimschoots gepubliceerd en kan dit issue gesloten worden.

Wel blijft nog even de vraag open of Slack ook een duurzame manier is om vragen en antwoorden beschikbaar te houden. Maar dat is een ander issue #73

**Comment by TCIMEddy** [comment]
@melsk-r Volgens mij kan deze nu door jou op close gezet worden

**Comment by melsk-r** [comment]
Inderdaad, ga ik doen.
