### ISSUE TITLE
Als beheerder wil ik dat duidelijk is welke activiteiten ik wel en welke actviteiten ik niet uitvoer.

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/api-beheer#71]
...zodat ik precies weet over welke kennis en software ik moet beschikken en er geen discussie kan ontstaan over mijn verantwoordelijkheden.

**Definition of ready**

- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg voor een sprint
- [x] Product Owner akkoord en voorzien van prio
- [x] Voorzien van Acceptatiecriteria
- [x] Voorzien van Definition of Done
- [x] Voorzien van taken
- [x] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [ ] Er zijn afspraken gemaakt over activiteiten die door beheerders worden uitgevoerd.
- [ ] Zo nodig duidelijkheid over activiteiten die wellicht in de toekomst nog naar de beheerder toegeschoven gaan worden.

**Oplossingsrichting**

...

**Acceptatiecriteria**

- [ ] Niet belemmerend werken voor beheer andere standaarden
- [ ] Er is een duidelijke lijst met door de beheerder(s) uit te voeren activiteiten.
- [ ] Er is tevens een duidelijke lijst met activiteiten die niet door de beheerder(s) worden uitgevoerd en die dus nog belegd moeten worden.

**Taken**

- [ ] Maak een lijst van alle, bij het beheren van de ZDS standaard, uit te voeren activiteiten. (@joeribekker, @michielverhoef, @melsk-r)
- [ ] Op basis van de bovenstaande lijst afspraken maken welke activiteiten wel en welke niet door de beheerder(s) worden uitgevoerd. (@joeribekker, @michielverhoef, @melsk-r)

**Comment by TCIMEddy** [comment]
@melsk-r Wil je dat ik deze ready maak? (Prima)

**Comment by melsk-r** [comment]
Ja graag want ik denk dat deze in de volgende sprint mee moet zodat we hier eerst duidelijkheid over kunnen creëren. Aan de hand van dit issue kunnen we dan bepalen aan welke issues we wel en aan welke we geen aandacht besteden.

**Comment by TCIMEddy** [comment]
@melsk-r Ik denk dat in het document beheer een stuk hieraan besteed moet worden. Hoeft niet in 1 keer goed te zijn maar gewoon twee kopje maken met wat doen we wel en wat doen we niet. (indien je denkt dat we regie doen dan doen we het ook)

**Comment by michielverhoef** [comment]
Het lijkt er op dat in #91 al een keuze voor werkzaamheden is gemaakt?

**Comment by melsk-r** [comment]
Ik heb een eerste versie opgenomen en een PR gemaakt.

**Comment by TCIMEddy** [comment]
@melsk-r wat mij betreft ook done

**Comment by melsk-r** [comment]
Ik sluit hem, maar ook hier zullen nog wel wijzigingen op komen in de loop van de tijd.
