### ISSUE TITLE
Demo Sprint 3 (21 maart 2019)

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-beheer#75]
Demo beheer 21 maart 2019

Feedback tijdens demo:

- hulp bij lopende implementaties
- Waar publiceren we? Alleen developer.nl ook op Gemma online? (Ja)
- Prioriteren van wensen en eisen
- Informatiemodel (in criteria apart benoemen?)
- Compatibiliteit van API en niet totaal
- RI in de vorm van een testomgeving om te kunnen spelen (sendbox)
- standaard op kwaliteitsniveau? Is API lab dan openbare consultatie, niet voldoende scherp
- Snelheid van ontwikkelen en versiebeheer
- 1 gemeenten (en specifiek noemen koppelen van 2 partijen)
- Ontkoppelen deployment en standaard…
- Autodiscovery
- Klant bepaalt nieuwe functionaliteit (gemeente)
- leverancier en gemeente moet voldoen aan standaard goed inprijzen! 
- Verplicht standaard!?
- API standaard is 'klein' t.o.v. Stuf
---
Aantekeningen Robert:
- De eis ‘Er moet minstens één API lab gehouden zijn om ervaringen van gebruikers te verzamelen’ moet aangepast worden. Het forum voor standaardisatie stelt als eis voor opname in de lijst met standaarden dat er een openbare consultatie is gehouden. De vraag is echter hoe je de openbare consultatie gaat inrichten. Dat zou je misschien in een API lab kunnen doen maar dan moet die betreffende API lab wel zo ingericht worden dat het aan de eisen van een openbare consultatie voldoet.
- De eis ‘Er is een (test) implementatie bij tenminste 1 gemeente gedaan’ moet iets worden als ‘Er is een (test) implementatie tussen tenminste 2 partijen gedaan’.
- Er moet snel geschakeld kunnen worden zodra er in een standaard tegen problemen aan wordt gelopen.
- John Rooijakkers zegt dat PR waarschijnlijk in de provider applicaties niet de gehele API’s gaan implementeren. Robert van Poelgeest had daar zijn bedenkingen over.
- De opdrachtgevers (gemeenten) zullen aan de leveranciers aan moeten gaan geven wat zij willen dat zal worden ingebouwd. Gemeenten kunnen daarmee een betere opdrachtgever zijn.
- John Rooijakkers zegt dat er een overzicht moet komen waarin staat welke partijen wat hebben geïmplementeerd.
- Het moet voor leveranciers duidelijk zijn hoe de prioriteiten zijn van de userstories in de backlog.
- Het moment van deployment moet losgekoppeld worden van het moment van …..?
- Volgens Johan Boer is er een verschil tussen een 'API' die backwards compatible wijzigingen heeft en een 'API standaard' die backwards compatible wijzigingen heeft.
- De overgang van de ene versie naar de andere versie moet behapbaar zijn voor leveranciers.
- De verbinding tussen leveranciers/gemeenten en de standaard moet levend gehouden worden.
- De demo was nog niet heel concreet.

Opmerkingen m.b.t. de demo:
- De sessie mag wat langer duren.
- De setting van de sessie mag beter (geen tafels)
- Gewenste onderwerpen:
  - Compliance model/convenant (governance)
  - Proces
  - Versiebeheer
  - Inzicht geven gebruik standaard
-----

Robert regelt uitnodiging + lokatie

Gemeenten (Die betrokken zijn bij andere projecten)
Leveranciers (Die betrokken zijn bij andere projecten)
Productowner Hugo, Henri, Cathy, Eelco
Ontwikkelaars: Johan, Maykin
Opdrachtgever Theo en Wishal
Scrummaster Jan Willem

Visie (@melsk-r )
Roadmap (@melsk-r , @TCIMEddy maakt plaatje)
Criteria voor in beheername (@michielverhoef @melsk-r)
Taken en verantwoordelijkheden (@michielverhoef @melsk-r)
Versiebeheer (@joeribekker )
Beheeromgeving (@kciredor @melsk-r)
Feedback en vragen (@TCIMEddy Mentimeter?)
Sluiting (@melsk-r )

Reserveonderwerp(en)
Ondersteuning

- Input vragen tijdens bijeenkomst maar ook op de backlog

11 maart 2019 generale repetitie…

**Comment by michielverhoef** [comment]
Wat wordt met dit issue bedoeld? Moeten we op vrijdag 1 februari ergens verschijnen en zo ja, waar? Is al duidelijk dat er een sprint demo gehouden wordt en wanneer zou die moeten zijn?

**Comment by joeribekker** [comment]
Belangrijke vragen maar ik denk dat minstens zo belangrijk is dat we na gaan denken over wat we kunnen laten zien na 2 sprints.

Hoewel ik mezelf vooral adviserend zie kan ik wel mijn visie geven op versiebeheer, major, minor, breaking changes, etc met de demo API tijdens een demo. Het grote plaatje van hoe een versie tot stand komt (proces) lijkt me een goed topic sowieso.

**Comment by TCIMEddy** [comment]
@michielverhoef @joeribekker @melsk-r @kciredor Ideeën voor de demo graag melden in dit issue zodat we a.s. donderdag met die input aan de slag kunnen.

**Comment by michielverhoef** [comment]
Donderdag 7 maart lijkt me geen goede datum: die dag is er ook een Common Ground 2-daagse waardoor een aantal belangrijke gasten voor wie we de demo gaan houden verhinderd zullen zijn.

Zelf denk ik dat een week (of 2) later veel beter zal passen. Dan is ook de eerste demo van developer.overheid.nl geweest zodat we daar ook een veel beter beeld bij hebben, aangezien dat ons publicatie mechanisme gaat worden (verwacht is).

**Comment by kciredor** [comment]
Mijn input zou in "Haven" kunnen liggen. Deze is echter enkel technisch, lijkt me nu niet direct aan de orde voor deze Demo.

**Comment by joeribekker** [comment]
Ik zou het hele verhaal beginnen met de taken van beheer, wat volgens mij goed in beheer.md staat omschreven.

**Comment by melsk-r** [comment]
> 
> 
> Ik zou het hele verhaal beginnen met de taken van beheer, wat volgens mij goed in beheer.md staat omschreven.

Mij lijkt juist beter om eerst de visie te schetsen als een kader waaraan de andere onderwerpen kunnen worden opgehangen. In die visie benoem ik dan dat er criteria zijn waaraan een standaard moet voldoen om in beheer genomen te kunnen worden maar ga daar niet dieper op in. Michiel kan die dan later verder uitdiepen. Ik benoem ook dat beheer diverse taken en verantwoordelijkheden heeft en dat sommige van die taken zelf uitgevoerd worden maar dat sommige ook betekent dat er alleen regie gevoerd wordt. Het verder uitdiepen van die taken kan Michiel dan weer doen. Zo misschien ool voor versiebeheer.

**Comment by joeribekker** [comment]
Oops ik bedoelde inderdaad na (of in) de visie.

**Comment by michielverhoef** [comment]
Ik heb de datum in titel en het issue aangepast ivm verplaatsen van de demo.

**Comment by JanWillemKooi** [comment]
Waar en hoe laat is de demo van donderdag, 21 maart gepland? En klopt het, dat ik geen uitnodiging heb ontvangen?

**Comment by melsk-r** [comment]
> Waar en hoe laat is de demo van donderdag, 21 maart gepland? En klopt het, dat ik geen uitnodiging heb ontvangen?

Jan Willem, ik ga nog na waarom jij geen uitnodiging hebt ontvangen en ook of anderen die gisteren ontbraken wel een uitnodiging hebben ontvangen.
