### ISSUE TITLE
Als gebruiker van een standaard wil ik dat versiebeheer zoals beschreven in de DSO API strategie aansluit bij de praktijk van standaardisatie

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/api-beheer#82]
...zodat zowel de API standaarden als de door basisregistraties geboden API's op dezelfde manier met versies omgaan.

NB. Dit zou zelfs al praktisch opgelost kunnen worden door niet alleen de major maar ook de minor versie op te nemen in de versie-url.

Taak voor @HenriKorver als deelnemer aan de DSO API strategie?

**Definition of ready**

- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg voor een sprint
- [ ] Product Owner akkoord en voorzien van prio
- [ ] Voorzien van Acceptatiecriteria
- [ ] Voorzien van Definition of Done
- [ ] Voorzien van taken
- [ ] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [ ] ...
- [ ] ...

**Oplossingsrichting**

...

**Acceptatiecriteria**

- [ ] Niet belemmerend werken voor beheer andere standaarden
- [ ] ...

**Taken**

- [ ] ... (@...)
- [ ] ... (@...)

**Comment by melsk-r** [comment]
@michielverhoef @TCIMEddy: Je geeft in de beschrijving aan dat het een taak is voor Henri maar het issue is wel aan mij toegekend. Ik vraag me dus af wat ik hier aan zou moeten doen. Als PO kan ik hier nl. ook niets mee aangezien het geen issue is dat in een van onze sprints opgenomen gaat worden. Ik ken hem dus maar even aan Eddy toe.

**Comment by TCIMEddy** [comment]
@melsk-r Volgens mij wordt versiebeheer uitgebreid behandeld in een andere user story. Ik close daarom deze.

**Comment by melsk-r** [comment]
Prima, wel even waarborgen dat dat verhaal overeenstemt met dat in de DSO API strategie.

**Comment by michielverhoef** [comment]
Het idee achter deze userstory is dat versiebeheer van standaarden ook past in de API strategie en niet alleen de API's geboden door Kadaster, BAG, NHR etc. (waarbij zij de provider implementeren) daarin passen. Bij de standaarden geldt bijvoorbeeld ook dat het voor kan komen dat een consumer een nieuwere versie van een API gebruikt dan een lokale provider bij een gemeente biedt.

In eerste instantie had ik hem mede toegekend aan Henri omdat hij de vertegenwoordiger in de DSO API strategie werkgroep is maar aangezien de openbare consultatie net gestart is kunnen we onze wensen eventueel altijd nog zelf direct bij de juiste werkgroep in brengen.
