### ISSUE TITLE
Als beheerder wil ik Docker en Wifi hebben op mijn laptop

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/api-beheer#83]
... zodat ik mijn werk kan doen.

De laptops van Michiel en Robert lijken niet lekker met Docker om te kunnen gaan. Robert geeft aan dat zijn laptop trager is geworden en beide geven aan dat Wifi nu niet meer lekker werkt.

Wat ik ga doen:

* Huidige laptop fixen
* Op een standaard VNG laptop (Wishal moet deze regelen) Docker werkend krijgen met uitleg
* Alternatieve of 2e laptop regelen

**Comment by joeribekker** [comment]
Voor mijn eigen referentie: Het betreft een HP Elitebook 840 G3

* https://community.spiceworks.com/topic/558002-problems-with-elitebook-840-laptops
* https://www.reddit.com/r/techsupport/comments/8bgmmi/wifi_disabled_and_cannot_enable_after/

**Comment by joeribekker** [comment]
Bij deze werkend gekregen op de laptop van Michiel.

Stappen:

1. Via Netwerk adapters, alle adapters uitgeschakeld.
2 Via apparaat beheer alle overbodige wifi en netwerk adapters verwijderd
3. Docker verwijderd
4. Docker verwijderd uit opstarten (stond er nog in maar doet waarschijnlijk niets)
5. Hyper-V verwijderd via Windows features
6. Adapters (wifi, bt en netwerk) weer aangezet (rest is weg als het goed is)
7. Docker Toolbox geinstalleerd

En.... werkt!

**Comment by melsk-r** [comment]
> 
> 
> Bij deze werkend gekregen op de laptop van Michiel.
> 
> Stappen:
> 
>     1. Via Netwerk adapters, alle adapters uitgeschakeld.
>        2 Via apparaat beheer alle overbodige wifi en netwerk adapters verwijderd
> 
>     2. Docker verwijderd
> 
>     3. Docker verwijderd uit opstarten (stond er nog in maar doet waarschijnlijk niets)
> 
>     4. Hyper-V verwijderd via Windows features
> 
>     5. Adapters (wifi, bt en netwerk) weer aangezet (rest is weg als het goed is)
> 
>     6. Docker Toolbox geinstalleerd
> 
> 
> En.... werkt!
> 
> Assign maar weer aan mij als het nog niet goed gaat.

Ik zal eens kijken of het a.d.h.v. dit lijstje gaat lukken.

**Comment by TCIMEddy** [comment]
@melsk-r Ik weet niet of we al een FAQ hebben maar daar zou dit een mooie voor zijn.

**Comment by michielverhoef** [comment]
Het bleek dat Robert op zijn machine de v-ethernet adapters niet weg kon gooien, blijkbaar hebben we toch andere rechten op onze eigen machines ...

Daarom hebben we toch maar docker for windows gedeinstalleerd, hyper-v uitgezet en na herstarten leek dat het wifi probleem opgelost.

Straks gaan we docker toolbox installeren en kijken of het nog steeds allemaal werkt.

**Comment by melsk-r** [comment]
> Daarom hebben we toch maar docker for windows gedeinstalleerd, hyper-v uitgezet en na herstarten leek dat het wifi probleem opgelost.

Wifi probleem is slechts deels opgelost. Activeren van wifi gaat nog steeds niet vlotjes. Maandag even met Joeri kijken of ik de drivers verwijderd krijg daarna kan ik Docker Toolbox installeren.

**Comment by joeribekker** [comment]
Maandag kijk ik er naar, first thing!

**Comment by michielverhoef** [comment]
Ik vrees dat bij mij de wifi problemen ook niet (meer) geheel opgelost zijn, ook niet met Docker Toolbox.

Maandag maar even kijken wat wijsheid is maar ik neig ernaar dit probleem vrij fundamenteel op te lossen:
1/ Laptop terug naar VNG standaard
2/ Laptop dual boot maken en Docker onder Linux draaien.

**Comment by melsk-r** [comment]
Vanochtend heeft Joeri op mijn laptop de overbodige adapters verwijderd en Docker Toolbox geïnstalleerd.
Het lijkt er op dat mijn wifi nu weer stabiel opereert. Ook kan ik tot nu toe goed met docker werken.

**Comment by ehotting** [comment]
Klinkt als een hele dure werkplekbeheerder  😛
