### ISSUE TITLE
Als beheerteam zorgen wij ervoor dat de OAS3 voor ZGW-API's gegeneerd kan worden vanuit de imvertor

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-beheer#91]
Imvertor gaat een rol spelen in het beheerproces. Daarom is het van belang dat voordat de API's/OAS3 in beheer genomen gaat worden toekomstige wijzigingen via de Imvertor in de OAS3 aangebracht moeten worden. Michiel heeft hier al een hele slag in geslagen. A.s. Maandag tijdens de stand-up de status bepalen.

**Comment by michielverhoef** [comment]
Eerst even afstemmen met @JohanBoer, hij heeft de laatste slagen aan de verschillende modellen gelmaakt.

**Comment by michielverhoef** [comment]
Een vraag: wordt het een taak voor beheer om de bestaande OAS3 bestanden te modelleren in UML in Enterprise Architect zodat we exact dezelfde OAS3 bestanden kunnen genereren?
Of wordt dit een taak die vanuit een ontwikkelproject opgepakt moet worden?

**Comment by melsk-r** [comment]
> 
> 
> Een vraag: wordt het een taak voor beheer om de bestaande OAS3 bestanden te modelleren in UML in Enterprise Architect zodat we exact dezelfde OAS3 bestanden kunnen genereren?
> Of wordt dit een taak die vanuit een ontwikkelproject opgepakt moet worden?

Je hebt gelijk, dit is geen taak voor beheer. Het ontwikkelproject ZGW moet de juiste UML modellen opleveren.

**Comment by TCIMEddy** [comment]
@melsk-r Verwerk je dit ook in het document beheer.md

**Comment by michielverhoef** [comment]
Ik stel voor dit issue te sluiten. Genereren vanuit de UML modellen is iets wat mogelijk gemaakt wordt wanneer bij het standaardisatie traject tijdens sprints de dan geldende inzichten in UML vastgelegd worden. Dit is gangbare praktijk in de wereld van software ontwikkeling dus dat zou geen probleem hoeven te zijn. Ook is dit geen top-down benadering, het UML diagram is de electronische versie van het bierviltje waarop een schetsje voor een issue uitgewerkt is. 

Vastleggen en documenteren dus, of we er daarna iets uit gaan genereren of dat uit de referentieimplementatie exporteren is niet zo spannend.
