### ISSUE TITLE
Werkzaamheden Beheer versus werkzaamheden OPS

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-beheer#96]
# Impediment

Op dit moment is het nog onduidelijk voor het scrumteam beheer wie er verantwoordelijk is voor de OPS-voorzieningen. Moeilijke kwestie maar moet wel duidelijkheid over komen. Wie beheert de 'werkbank' voor de teams (OTAP, Testfaciliteiten, cloud etc.). We hebben een aantal user stories waarin zaken geregeld moeten m.b.t. inrichting en kennis opdoen. We hebben eerst een uitspraak nodig om zaken op te kunnen pakken.

**Comment by wishalg** [comment]
Ik denk dat Roderick ons in de werkzaamheden OPS goed kan ondersteunen @kciredor

**Comment by kciredor** [comment]
Mijn voorstel volgt zeer spoedig, waarna ik hopelijk van start kan. Het zal al met al wel tijd in beslag nemen, vanaf nul Ops inrichten voor teams, of eigenlijk de onderliggende infra (die er nu niet is).

**Comment by TCIMEddy** [comment]
Dus is dit impediment opgelost en close
